/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import promedianainterfaz.Materia;
import promedianainterfaz.Nota;
import promedianainterfaz.Semestre;

/**
 *
 * @author brayan
 */
public class VentanaNuevaMateria extends javax.swing.JFrame {
    
    private VentanaSemestre ventanaSemestre;
    private Semestre semestre = new Semestre();

    public VentanaNuevaMateria(Semestre semestre) {
        initComponents();

        this.semestre = semestre; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        txtCreditosNuevaMateria = new javax.swing.JTextField();
        txtNombreNuevaMateria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(112, 129, 148));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SF UI Display", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Nombre de la Materia");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("SF UI Display", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Creditos de la Materia");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        btnSiguiente.setBackground(new java.awt.Color(68, 68, 68));
        btnSiguiente.setFont(new java.awt.Font("SF UI Display", 0, 18)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(204, 204, 204));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        txtCreditosNuevaMateria.setBackground(new java.awt.Color(68, 68, 68));
        txtCreditosNuevaMateria.setFont(new java.awt.Font("SF UI Display", 0, 18)); // NOI18N
        txtCreditosNuevaMateria.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtCreditosNuevaMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 210, 30));

        txtNombreNuevaMateria.setBackground(new java.awt.Color(68, 68, 68));
        txtNombreNuevaMateria.setFont(new java.awt.Font("SF UI Display", 0, 18)); // NOI18N
        txtNombreNuevaMateria.setForeground(new java.awt.Color(204, 204, 204));
        txtNombreNuevaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreNuevaMateriaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreNuevaMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreNuevaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreNuevaMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreNuevaMateriaActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if (txtCreditosNuevaMateria.getText().equalsIgnoreCase("") || txtNombreNuevaMateria.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(rootPane, "Ups! se te olvido llenar algo");
        } else {
            try {
                // Modelo de materias vacio
                DefaultListModel<Nota> notas = new DefaultListModel<>();
                int creditos = Integer.parseInt(txtCreditosNuevaMateria.getText());
                Materia nuevaMateria = new Materia(txtNombreNuevaMateria.getText(), creditos, notas);

                //logica 
                ventanaSemestre = new VentanaSemestre(nuevaMateria, semestre);

                this.dispose();
                ventanaSemestre.setVisible(true);
                ventanaSemestre.setLocationRelativeTo(null);

            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(rootPane, "ups! Ingresaste un dato invalido");
            }
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCreditosNuevaMateria;
    private javax.swing.JTextField txtNombreNuevaMateria;
    // End of variables declaration//GEN-END:variables
}
