/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import promedianainterfaz.Materia;
import promedianainterfaz.Nota;
import promedianainterfaz.Semestre;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author brayan
 */
public class VentanaNuevaMateria extends javax.swing.JFrame {

    private VentanaSemestre ventanaSemestre;
    private Semestre semestre = new Semestre();

    public VentanaNuevaMateria(Semestre semestre) {
        initComponents();

        this.semestre = semestre;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSiguiente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreNuevaMateria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCreditosNuevaMateria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(112, 129, 148));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSiguiente.setBackground(new java.awt.Color(200, 216, 231));
        btnSiguiente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(51, 51, 51));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        jPanel2.setBackground(new java.awt.Color(112, 129, 148));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Nombre de la Materia");

        txtNombreNuevaMateria.setBackground(new java.awt.Color(68, 68, 68));
        txtNombreNuevaMateria.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtNombreNuevaMateria.setForeground(new java.awt.Color(204, 204, 204));
        txtNombreNuevaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreNuevaMateriaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Creditos de la Materia");

        txtCreditosNuevaMateria.setBackground(new java.awt.Color(68, 68, 68));
        txtCreditosNuevaMateria.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCreditosNuevaMateria.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtCreditosNuevaMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(txtNombreNuevaMateria))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreNuevaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCreditosNuevaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 360, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreNuevaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreNuevaMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreNuevaMateriaActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if (txtCreditosNuevaMateria.getText().equalsIgnoreCase("") || txtNombreNuevaMateria.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(rootPane, "Ups! se te olvido llenar algo");
        } else {
            try {
                // Modelo de materias vacio
                DefaultListModel<Nota> notas = new DefaultListModel<>();
                int creditos = Integer.parseInt(txtCreditosNuevaMateria.getText());
                Materia nuevaMateria = new Materia(txtNombreNuevaMateria.getText(), creditos, notas);

                //se agrega la materia nueva al semestre
                semestre.getMaterias().addElement(nuevaMateria);

                //se pasa el semestre a la venta pricipal
                ventanaSemestre = new VentanaSemestre(semestre);

                //se hace visible la ventana principal
                ventanaSemestre.setVisible(true);
                ventanaSemestre.setLocationRelativeTo(null);

                this.dispose();

            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(rootPane, "ups! Ingresaste un dato invalido");
            }
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCreditosNuevaMateria;
    private javax.swing.JTextField txtNombreNuevaMateria;
    // End of variables declaration//GEN-END:variables
}
