package GUI;

/**
 *
 * @author brayan
 */
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import promedianainterfaz.Nota;
import promedianainterfaz.Materia;
import promedianainterfaz.Semestre;

public class VentanaNuevaNota extends javax.swing.JFrame {

    private DefaultListModel<Nota> notas = new DefaultListModel<>();
    private Materia materia = new Materia("", 0, notas);
    //se crea una materia vacia para despues modificarla

    private Semestre semestre = new Semestre();
    //semetre vacio para llenarlo apartir del parametro del constructor

    private int index;
    // me dira con que indice de la lista de materias estoy tabajando

    private int indexNota = -1;
    // servira si lo que se quiere es si es editar una nota en ves de crear una
    // nueva

    public VentanaNuevaNota(Semestre semestre, int index) {
        initComponents();

        this.index = index;

        //se cambian los valores de la materia vacia a los de la materia seleccionada
        this.materia = semestre.getMaterias().getElementAt(index);

        //se cambia el semestre vacio por el semestre que pase por parametro
        this.semestre = semestre;
    }

    //constructor que solo se utlizara para editar una nota
    public VentanaNuevaNota(Semestre semestre, int indexMateria, int indexNota) {
        initComponents();

        // se editan los textos de manera que sea mas consecuente con la accion
        // que se esta realizndo (Editar una Nota)
        lblNombre.setText("Edite el nombre de la nota");
        
        lblProcentaje.setText("Edite el porcentaje");
  
        
        lblCalificacion.setText("Edite su calificacion");

        this.index = index;

        //se cambian los valores de la materia vacia a los de la materia seleccionada
        this.materia = semestre.getMaterias().getElementAt(index);

        //se cambia el semestre vacio por el semestre que pase por parametro
        this.semestre = semestre;

        //se indica cual nota es la que se quiere editar
        this.indexNota = indexNota;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSiguienteNuevaNota = new javax.swing.JButton();
        lblCalificacion = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblProcentaje = new javax.swing.JLabel();
        txtCalificacionNuevaNota = new javax.swing.JTextField();
        txtNombreNuevaNota = new javax.swing.JTextField();
        txtPorcentajeNuevaNota = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(148, 112, 112));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSiguienteNuevaNota.setBackground(new java.awt.Color(231, 200, 200));
        btnSiguienteNuevaNota.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnSiguienteNuevaNota.setForeground(new java.awt.Color(51, 51, 51));
        btnSiguienteNuevaNota.setText("Siguente");
        btnSiguienteNuevaNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteNuevaNotaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguienteNuevaNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        lblCalificacion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblCalificacion.setForeground(new java.awt.Color(51, 51, 51));
        lblCalificacion.setText("calificacion");
        jPanel1.add(lblCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        lblNombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(51, 51, 51));
        lblNombre.setText("Nombre de la nueva nota");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 20));

        lblProcentaje.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblProcentaje.setForeground(new java.awt.Color(51, 51, 51));
        lblProcentaje.setText("porcentaje de la nueva nota");
        jPanel1.add(lblProcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txtCalificacionNuevaNota.setBackground(new java.awt.Color(68, 68, 68));
        txtCalificacionNuevaNota.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCalificacionNuevaNota.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtCalificacionNuevaNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 230, -1));

        txtNombreNuevaNota.setBackground(new java.awt.Color(68, 68, 68));
        txtNombreNuevaNota.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtNombreNuevaNota.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtNombreNuevaNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 230, -1));

        txtPorcentajeNuevaNota.setBackground(new java.awt.Color(68, 68, 68));
        txtPorcentajeNuevaNota.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtPorcentajeNuevaNota.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtPorcentajeNuevaNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteNuevaNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteNuevaNotaActionPerformed
        // boton para agregar la nueva nota a la materia 
        try {
            double calificacion = Double.parseDouble(txtCalificacionNuevaNota.getText());
        } catch (Exception e) {
        }

        // se condiciona que los huecos de texto no esten vacios 
        if (txtCalificacionNuevaNota.getText().equals("") || txtNombreNuevaNota.getText().equals("") || txtPorcentajeNuevaNota.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Ups! Se te olvido ingresar algo");
        } else {
            try {
                //se controla las exepciones de tipo argumento ilegal

                String nombre = txtNombreNuevaNota.getText();
                double porcentaje = Double.parseDouble(txtPorcentajeNuevaNota.getText());
                double calificacion = Double.parseDouble(txtCalificacionNuevaNota.getText());
      
                // con este condicional se verifica que la calificacion este dentro de los limites establecios por el usuario
                if (calificacion >= semestre.getLimiteInferior() && calificacion <= semestre.getLimiteSuperior() ) {
                    //creacion de la nueva nota 
                    
                    
                    //Se valida que la condición no sobrepase los valores negativos y mayores de 100
                    if (porcentaje >= 0 && porcentaje <= 100){
 
                    
                    Nota nuevaNota = new Nota(nombre, porcentaje, calificacion);

                    //se ingresa la nueva nota al semestre 
                    // si no hay ningun indice de nota entonces 
                    // se agregara una nueva nota
       
                    
                    if (indexNota == -1) {
                        semestre.getMaterias().getElementAt(index).getNotas().addElement(nuevaNota);

                        // De lo contrario se editará la nota en el indice especificado
                    } else {
                        semestre.getMaterias().getElementAt(index).getNotas().set(indexNota, nuevaNota);

                    }


                    // se pasa el nuevos semestre con la nueva nota a la ventana materia y se hace visible; 
                    VentanaMateria ventanaMateria = new VentanaMateria(semestre, index);
                    ventanaMateria.setVisible(true);
                    ventanaMateria.setLocationRelativeTo(null);

                    this.dispose();

                    // de lo contrario sí si se paso el indice entonces 
                    // lo pasado por teclado se guardará en la materia del
                    // indice indicadoF
                    
                    }else{
                    JOptionPane.showMessageDialog(rootPane, "El porcentaje no puede ser negativo y menor que cien");
                    txtPorcentajeNuevaNota.setText("");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "La calificacion que pusiste esta fuera de los limites que especificaste");
                    txtCalificacionNuevaNota.setText("");
                }
                
                
                // con este condicional se verifica que la calificacion este dentro de los limites establecios por el usuario

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Ups! Ingresaste un dato invalido");
                txtCalificacionNuevaNota.setText("");
                txtPorcentajeNuevaNota.setText("");
            }
        }
    }//GEN-LAST:event_btnSiguienteNuevaNotaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguienteNuevaNota;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCalificacion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblProcentaje;
    private javax.swing.JTextField txtCalificacionNuevaNota;
    private javax.swing.JTextField txtNombreNuevaNota;
    private javax.swing.JTextField txtPorcentajeNuevaNota;
    // End of variables declaration//GEN-END:variables
}
